server:
  port: 9092
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keys/MyServer.pfx
    key-store-password: pg@123

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/bankpg
    username: root
    password: root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  application:
    name: Addrespg-service
  cache:
    type: redis
    redis:
      cache-null-values: true
  data:
    redis:
      host: localhost
      port: 6379

